# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nb_dev <- function(Y, MU, Phi, naind) {
    .Call('_nbfar_nb_dev', PACKAGE = 'nbfar', Y, MU, Phi, naind)
}

get_sc <- function(X, Y) {
    .Call('_nbfar_get_sc', PACKAGE = 'nbfar', X, Y)
}

grad_eta_nb <- function(Y, eta, Phi) {
    .Call('_nbfar_grad_eta_nb', PACKAGE = 'nbfar', Y, eta, Phi)
}

grad_mu_nb <- function(Y, mu, Phi) {
    .Call('_nbfar_grad_mu_nb', PACKAGE = 'nbfar', Y, mu, Phi)
}

grad_mu_nb_uv <- function(Y, mu, Phi, d2l) {
    .Call('_nbfar_grad_mu_nb_uv', PACKAGE = 'nbfar', Y, mu, Phi, d2l)
}

update_mu_phi <- function(Y, mu, Phi) {
    .Call('_nbfar_update_mu_phi', PACKAGE = 'nbfar', Y, mu, Phi)
}

update_mu_alpha <- function(Y, mu, Phi, naind) {
    .Call('_nbfar_update_mu_alpha', PACKAGE = 'nbfar', Y, mu, Phi, naind)
}

nbrrr_likelihood <- function(Y, MU, ETA, Phi, naind) {
    .Call('_nbfar_nbrrr_likelihood', PACKAGE = 'nbfar', Y, MU, ETA, Phi, naind)
}

mySdiff <- function(x, y) {
    .Call('_nbfar_mySdiff', PACKAGE = 'nbfar', x, y)
}

nbrrr_cpp <- function(Y, X0, rnk, cindex, ofset, Zini, PhiIni, Cini, control, msind, naind) {
    .Call('_nbfar_nbrrr_cpp', PACKAGE = 'nbfar', Y, X0, rnk, cindex, ofset, Zini, PhiIni, Cini, control, msind, naind)
}

get_sv1 <- function(xyx, ue, q) {
    .Call('_nbfar_get_sv1', PACKAGE = 'nbfar', xyx, ue, q)
}

get_sv2 <- function(xyx, Y, q) {
    .Call('_nbfar_get_sv2', PACKAGE = 'nbfar', xyx, Y, q)
}

get_sv <- function(xyx, ue, q, tem_uvec) {
    .Call('_nbfar_get_sv', PACKAGE = 'nbfar', xyx, ue, q, tem_uvec)
}

softThres <- function(x, lambda) {
    .Call('_nbfar_softThres', PACKAGE = 'nbfar', x, lambda)
}

softT <- function(x, lambda) {
    .Call('_nbfar_softT', PACKAGE = 'nbfar', x, lambda)
}

nzcount <- function(x) {
    .Call('_nbfar_nzcount', PACKAGE = 'nbfar', x)
}

nbzerosol_cpp <- function(Y, X0, ofset, control, msind, naind) {
    .Call('_nbfar_nbzerosol_cpp', PACKAGE = 'nbfar', Y, X0, ofset, control, msind, naind)
}

nbfar_cpp <- function(Y, Xm, nlam, cindex, ofset, initw, Dini, Zini, PhiIni, Uini, Vini, lmax, control, msind, naind, maxit, epsilon) {
    .Call('_nbfar_nbfar_cpp', PACKAGE = 'nbfar', Y, Xm, nlam, cindex, ofset, initw, Dini, Zini, PhiIni, Uini, Vini, lmax, control, msind, naind, maxit, epsilon)
}

cv_nbfar_cpp <- function(Y, Xm, nlam, cindex, ofset, initw, Zini, PhiIni, xx, lmax, control, maxit, epsilon, nfold) {
    .Call('_nbfar_cv_nbfar_cpp', PACKAGE = 'nbfar', Y, Xm, nlam, cindex, ofset, initw, Zini, PhiIni, xx, lmax, control, maxit, epsilon, nfold)
}

cv_nbfar_par <- function(Y, Xm, nlam, cindex, ofset, initw, Zini, PhiIni, xx, lmax, control, maxit, epsilon, nfold) {
    .Call('_nbfar_cv_nbfar_par', PACKAGE = 'nbfar', Y, Xm, nlam, cindex, ofset, initw, Zini, PhiIni, xx, lmax, control, maxit, epsilon, nfold)
}

